theme = "rose_pine_minimal"

# Options
[editor]
line-number = "relative"
popup-border = "all"
end-of-line-diagnostics = "hint"
true-color = true

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "disable"

[editor.gutters.line-numbers]
min-width = 1

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "â–"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["workspace-diagnostics", "selections", "register", "position", "file-encoding"]

# Mapping
[keys.normal]
C-r = ":reload-all"
C-s = ":write"
A-2 = [ "file_explorer"]
A-3 = [ ":write-all", ":insert-output lazygit >/dev/tty", ":redraw", ":reload-all" ]
